"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-14 08:23:03.902212
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_slug'), ['slug'], unique=True)

    op.create_table('passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(length=1024), nullable=False),
    sa.Column('public_key', sa.LargeBinary(length=1024), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=128), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passkeys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passkeys'))
    )
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkeys_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_passkeys_user_id'), ['user_id'], unique=False)

    op.create_table('pending_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_logins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_logins'))
    )
    with op.batch_alter_table('pending_logins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_logins_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_logins_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=256), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('patient_birth_date', sa.String(length=16), nullable=True),
    sa.Column('patient_sex', sa.String(length=4), nullable=True),
    sa.Column('study_date', sa.String(length=8), nullable=True),
    sa.Column('study_time', sa.String(length=16), nullable=True),
    sa.Column('study_description', sa.String(length=256), nullable=True),
    sa.Column('accession_number', sa.String(length=64), nullable=True),
    sa.Column('referring_physician', sa.String(length=256), nullable=True),
    sa.Column('study_id', sa.String(length=32), nullable=True),
    sa.Column('modalities', sa.String(length=128), nullable=False),
    sa.Column('num_series', sa.Integer(), nullable=False),
    sa.Column('num_instances', sa.Integer(), nullable=False),
    sa.Column('dir_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_studies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies')),
    sa.UniqueConstraint('user_id', 'study_instance_uid', name='uq_study_user_uid')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studies_study_date'), ['study_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_study_instance_uid'), ['study_instance_uid'], unique=False)
        batch_op.create_index('ix_studies_user_date', ['user_id', 'study_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_studies_user_id'), ['user_id'], unique=False)

    op.create_table('totp_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_encrypted', sa.LargeBinary(length=512), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_totp_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_totp_credentials'))
    )
    with op.batch_alter_table('totp_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totp_credentials_user_id'), ['user_id'], unique=True)

    op.create_table('upload_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('source_names', sa.Text(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('study_uids', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_upload_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_jobs'))
    )
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_style', sa.String(length=16), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=False),
    sa.Column('use_gravatar', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('webauthn_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.LargeBinary(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_webauthn_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webauthn_challenges'))
    )
    with op.batch_alter_table('webauthn_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webauthn_challenges_challenge'), ['challenge'], unique=False)
        batch_op.create_index(batch_op.f('ix_webauthn_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_instance_uid', sa.String(length=64), nullable=False),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('series_description', sa.String(length=256), nullable=True),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('body_part_examined', sa.String(length=64), nullable=True),
    sa.Column('protocol_name', sa.String(length=128), nullable=True),
    sa.Column('series_date', sa.String(length=8), nullable=True),
    sa.Column('series_time', sa.String(length=16), nullable=True),
    sa.Column('num_instances', sa.Integer(), nullable=False),
    sa.Column('num_frames_total', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('is_multiframe', sa.Boolean(), nullable=False),
    sa.Column('is_reconstructable', sa.Boolean(), nullable=False),
    sa.Column('is_viewable', sa.Boolean(), nullable=False),
    sa.Column('mpr_orientation', sa.String(length=192), nullable=True),
    sa.Column('mpr_instance_count', sa.Integer(), nullable=False),
    sa.Column('slice_thickness', sa.Float(), nullable=True),
    sa.Column('computed_slice_spacing', sa.Float(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('dir_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_series_study_id_studies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_series_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('user_id', 'series_instance_uid', name='uq_series_user_uid')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_series_instance_uid'), ['series_instance_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_study_id'), ['study_id'], unique=False)
        batch_op.create_index('ix_series_study_number', ['study_id', 'series_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_user_id'), ['user_id'], unique=False)

    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(length=64), nullable=False),
    sa.Column('sop_class_uid', sa.String(length=64), nullable=True),
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('number_of_frames', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('bits_allocated', sa.Integer(), nullable=True),
    sa.Column('samples_per_pixel', sa.Integer(), nullable=False),
    sa.Column('photometric_interpretation', sa.String(length=32), nullable=True),
    sa.Column('transfer_syntax_uid', sa.String(length=64), nullable=False),
    sa.Column('image_position_patient', sa.String(length=96), nullable=True),
    sa.Column('image_orientation_patient', sa.String(length=192), nullable=True),
    sa.Column('pixel_spacing', sa.String(length=64), nullable=True),
    sa.Column('slice_location', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_instances_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_instances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('user_id', 'sop_instance_uid', name='uq_instance_user_uid')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_series_id'), ['series_id'], unique=False)
        batch_op.create_index('ix_instances_series_order', ['series_id', 'instance_number', 'sop_instance_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_sop_instance_uid'), ['sop_instance_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_user_id'))
        batch_op.drop_index(batch_op.f('ix_instances_sop_instance_uid'))
        batch_op.drop_index('ix_instances_series_order')
        batch_op.drop_index(batch_op.f('ix_instances_series_id'))

    op.drop_table('instances')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_user_id'))
        batch_op.drop_index('ix_series_study_number')
        batch_op.drop_index(batch_op.f('ix_series_study_id'))
        batch_op.drop_index(batch_op.f('ix_series_series_instance_uid'))

    op.drop_table('series')
    with op.batch_alter_table('webauthn_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webauthn_challenges_user_id'))
        batch_op.drop_index(batch_op.f('ix_webauthn_challenges_challenge'))

    op.drop_table('webauthn_challenges')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_jobs_user_id'))

    op.drop_table('upload_jobs')
    with op.batch_alter_table('totp_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totp_credentials_user_id'))

    op.drop_table('totp_credentials')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studies_user_id'))
        batch_op.drop_index('ix_studies_user_date')
        batch_op.drop_index(batch_op.f('ix_studies_study_instance_uid'))
        batch_op.drop_index(batch_op.f('ix_studies_study_date'))

    op.drop_table('studies')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token'))

    op.drop_table('sessions')
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_user_id'))

    op.drop_table('recovery_codes')
    with op.batch_alter_table('pending_logins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_logins_user_id'))
        batch_op.drop_index(batch_op.f('ix_pending_logins_token'))

    op.drop_table('pending_logins')
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkeys_user_id'))
        batch_op.drop_index(batch_op.f('ix_passkeys_credential_id'))

    op.drop_table('passkeys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_slug'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
